version: "3"
services:
  kode:
    build:
      context: .
      dockerfile: Dockerfile
    image: koder:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - pg
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgres://postgres:docker@172.38.1.20/kode
      OAUTHAPP_GITHUB_CLIENT_ID: test
      OAUTHAPP_GITHUB_CLIENT_SECRET: test
      OAUTHAPP_GITHUB_REDIRECT_URI: http://kode.konnector.local/oauth-github/auth
      DEBUG: 'true'
      SECURITY_SALT: test
    networks:
      testing_net:
        ipv4_address: 172.38.1.10

  pg:
    image: postgres:latest
    ports:
    - 5432:5432
    volumes:
      - db_data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kode
    networks:
      testing_net:
        ipv4_address: 172.38.1.20
volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.38.0.0/16
